### PR TITLE
guides: deployment: add doc about ROOT_URL

### PR DESCRIPTION
**Pull request by Castavo**

### CODE REVIEW

**Comment by multun** [comment]
I'm pretty sure more changes are needed to deploy OSRD on the internet using docker-compose. The docker compose setup is designed for development only: no authentication is supported, the front-end is served in development mode (rebuilt on the fly).

It's just not a good idea.

**Review by Khoyo — APPROVED** [review]

**Review by ElysaSrc — CHANGES_REQUESTED** [review]
I feel these changes are not required anymore since ROOT_URL is not used anymore : the gateway serves both on the same domain and the front uses a relative path. This setup prevents the need for setting the url and also prevents a bunch of CORS issues.

**Comment by Castavo** [comment]
@ElysaSrc neat ! Then should I close the PR completely or keep it to add only the detail about the docker-compose deployment being a tad unsafe / not protection ready ?

**Comment by ElysaSrc** [comment]
> @ElysaSrc neat ! Then should I close the PR completely or keep it to add only the detail about the docker-compose deployment being a tad unsafe / not protection ready ?

As you wish, adding a word about the docker compose deployment being unfit for production is a good idea.

**Comment by Khoyo** [comment]
> I feel these changes are not required anymore since ROOT_URL is not used anymore : the gateway serves both on the same domain and the front uses a relative path

It shouldn't be but it is... (editoast uses it to determine the url the layers are served from)

**Comment by Castavo** [comment]
Dang
So it's a bug ?

**Comment by Castavo** [comment]
@ElysaSrc at least we can merge the warning

**Comment by Khoyo** [comment]
Discussed with @flomonster, ROOT_URL is still here because we can't give relative URLs to MapLibre... So it's probably here to stay

**Comment by ElysaSrc** [comment]
Yes since it's still in use you can merge the PR like it was the first time.

Sorry for the confusion.

**Review by ElysaSrc — APPROVED** [review]

**Pull request merged**
