### PR TITLE
fix: doc: preamble.fr.md spelling ...

### PR DESCRIPTION
**Pull request by SergeCroise**
- open-source
- pour discuter
- repose sur

### CODE REVIEW

**Comment by SergeCroise** [comment]
@flomonster , please review!

**Review by flomonster — APPROVED** [review]
LGTM

**Comment by flomonster** [comment]
> @flomonster , please review!

Thanks for all your contributions. You should be able to add a reviewer to your PR. This notify the person directly.

**Comment by SergeCroise** [comment]
> > @flomonster , please review!
> 
> Thanks for all your contributions. You should be able to add a reviewer to your PR. This notify the person directly.

unfortunately, I do not know how...

**Pull request merged**
